# Generated by Django 4.2.10 on 2025-05-15 03:18

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.TextField(unique=True)),
                ('description_md', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('difficulty', models.TextField(blank=True, null=True)),
                ('time_thresholds', models.JSONField()),
                ('solution_templates', models.JSONField()),
                ('reference_solutions', models.JSONField()),
                ('harness_eval_files', models.JSONField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'problems',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField()),
                ('code', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField()),
                ('status', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('memory_kb', models.IntegerField(blank=True, null=True)),
                ('passed', models.BooleanField()),
                ('rank', models.TextField(blank=True, null=True)),
                ('raw_results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.problem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
    ]
